---
version: "3.9"
services:
  # azure storage emulator
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
      # blob
      - "10000:10000"
      # queue
      - "10001:10001"
  # webhook server
  webhook:
    build:
      context: .
      target: webhook
    environment:
      LOCAL: true
    env_file:
      - async_request_reply_pattern/webhook/secrets.env
  worker:
    image: python:3.11