version: "3.8"
services:
  saas1:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: saas
    ports:
      - "80"
  saas2:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: saas
    ports:
      - "80"
  saas3:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: saas
    ports:
      - "80"
